### ISSUE TITLE
usage of predicted value

### ISSUE THREAD

**Issue by pedefe** [piercus/kalman-filter#14]
Hello,
In one of your sample, you use 'predicted' as parameter.
```
const correctedState = kFilter.correct({
	predicted,
	observation
	});
```
Where is this var coming from ?
Best regards.

**Comment by pedefe** [comment]
Ok, I understand. You want write 'predictedState'. I close.

**Comment by piercus** [comment]
@pedefe if there is something unclear or a mistake in the documentation, i would be glad if you open a pull request to correct it.

Thank you for your help

**Comment by pedefe** [comment]
Hello,
Just change 'predicted' to 'predictedState' in samples;
Perharps can you explain the content of returned data like 'predictedState' and 'correctedState';
Best regards.
