### ISSUE TITLE
The argument is not a state 

### ISSUE THREAD

**Issue by Ivan-Kayn** [piercus/kalman-filter#23]
I am trying to use kalman filter for gps but by using your examples with predict and correct functions I got error "The argument is not a state. Tips: maybe you are using 2 different version of kalman-filter in your npm deps tree". It happens with kFilter.predict(...)
It happens just by defining new kFilter and using example from documentation: 
````
const kFilter = new KalmanFilter({
  observation: {
    sensorDimension: 2,
    name: "sensor"
  },
  dynamic: {
    name: "constant-position", // observation.sensorDimension == dynamic.dimension
    covariance: [50, 50] // equivalent to diag([3, 4])
  }
});
let previousCorrected = null;
const results = [];
observations.forEach(observation => {
	const predictedState = kFilter.predict({
		previousCorrected
	});

	 const correctedState = kFilter.correct({
		predictedState,
		observation
	});

	results.push(correctedState.mean);

	// update the previousCorrected for next loop iteration
	previousCorrected = correctedState
});
````
Am I doing something wrong?

**Comment by Ivan-Kayn** [comment]
I find out what was wrong from your demo, needed to get predicted from kf.predict=() and use them after for kf.correct as first argument. Sorry for question.

**Comment by piercus** [comment]
Hello @Ivan-Kayn 

I'm glad you have been able to fix it by yourself :-)

If you have any suggestion to improve the README.md in order to be more explicit and clear, do not hesitate to suggest a PR.
