### ISSUE TITLE
online kalman filter

### ISSUE THREAD

**Issue by chfrjgfl** [piercus/kalman-filter#47]
Hello, trying to run this example

-----------------------
```
// online kalman filter
let previousCorrected = null;
const results = [];
observations.forEach(observation => {
	const predictedState = kFilter.predict({
		previousCorrected
	});

	 const correctedState = kFilter.correct({
		predicted,
		observation
	});

	results.push(correctedState.mean);

	// update the previousCorrected for next loop iteration
	previousCorrected = correctedState
});

console.log(results);
```
---------------------------------

got  `ReferenceError: predicted is not defined`

Changing  `predicted `  to `predictedState `,  got 

```
TypeError: The argument is not a state 
Tips: maybe you are using 2 different version of kalman-filter in your npm deps tree
```

Meanwhile, the function  `kFilter.filterAll(observation)`  works well.
I am new to programming, so this is beyond my comprehension(yet). Could you please help me fix this.

Thank you for the library!

**Comment by chfrjgfl** [comment]
I changed   `predictedState   `  to  `predicted `,  and it worked properly.

**Comment by piercus** [comment]
Hello @chfrjgfl thanks for reporting an issue, I'm glad you fixed it !

It would be great if you can open a PR to fix the example in README.md

**Comment by chfrjgfl** [comment]
Hi, I'm sorry I dont know what PR is ((

вс, 13 нояб. 2022 г., 22:50 Colle ***@***.***>:

**Comment by piercus** [comment]
Pull request : https://github.com/piercus/kalman-filter/pulls
