### ISSUE TITLE
how to use in browser

### ISSUE THREAD

**Issue by whlysu** [piercus/kalman-filter#7]
i can't find the kalman-filter.min.js,
how it to use in browser?
and i can‘’t package this source

**Comment by piercus** [comment]
Hello @whlysu,

Thanks for your feedback.

You are right, this is something that should be added here.
For the web demo, i'm currently using browserify (see https://github.com/piercus/kalman-filter/blob/master/package.json#L9)

I will package kalman-filter.min.js and kalman-filter.js soon, and also publish a bower package.

**Comment by AnadiTaylor** [comment]
Hello Piercus.
Thanks for this repo, awesome!
Can you tell me how to use your Kalman filter in a browser please? I am not running Node.
Thanks in advance,
Anadi.

**Comment by piercus** [comment]
Hello @AnadiTaylor @whlysu , 

Thanks for the feedback, sorry for the late response.
I've just added the browser distributions of the files.

I have added some [documentation](https://github.com/piercus/kalman-filter#browser-usage).

Please confirm it is working on your side.

**Comment by AnadiTaylor** [comment]
Hello Colle.
Thank you for uploading the browser version.
I am having an issue, I have the following GPS lat/long data:

   1. 0: (2) ["51.45265869", "-0.25525714"]
   2. 1: (2) ["51.45265928", "-0.25525684"]
   3. 2: (2) ["51.45268013", "-0.25528912"]
   4. 3: (2) ["51.45270216", "-0.25531690"]
   5. 4: (2) ["51.45272217", "-0.25534272"]
   6. 5: (2) ["51.45274237", "-0.25536755"]
   7. 6: (2) ["51.45276016", "-0.25538990"]
   8. 7: (2) ["51.45277829", "-0.25541072"]
   9. 8: (2) ["51.45279597", "-0.25542977"]
   10. 9: (2) ["51.45281192", "-0.25544706"]
   11. 10: (2) ["51.45282625", "-0.25546321"]

I am passing this through the Kalman filter:

var  {KalmanFilter}  = kalmanFilter;
var kFilter = new KalmanFilter({
observation: 2,
dynamic: 'constant-speed'
});
var res = kFilter.filterAll(arrayTimes);

And I get the following error:

Uncaught TypeError: e.map is not a function
    at kalman-filter.min.js:1
    at Array.map (<anonymous>)
    at t.exports (kalman-filter.min.js:1)
    at t.exports (kalman-filter.min.js:1)
    at t.exports.correct (kalman-filter.min.js:1)
    at t.exports.correct (kalman-filter.min.js:1)
    at t.exports.filterAll (kalman-filter.min.js:1)

Can you help with this. I am happy to pay you for your time.

Thanks.
Anadi.


[image: Anadi James Taylor]    Anadi James Taylor
Suite 298
28 Old Brompton Road,
South Kensington,
London
SW7 3SS

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/06/21,
06:11:56 PM

**Comment by piercus** [comment]
I feel you are using array of string instead of an array of numbers.

By changing your 'arrayTimes' to arrays of numbers, it should work (see https://codepen.io/piercus/pen/yLVOxjE?editors=1111)

**Comment by AnadiTaylor** [comment]
Thank you Colle,
That worked. I will respond to your Twitter message.

Best wishes,
Anadi.



[image: Anadi James Taylor]    Anadi James Taylor
Suite 298
28 Old Brompton Road,
South Kensington,
London
SW7 3SS

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/07/21,
05:21:11 PM

**Comment by AnadiTaylor** [comment]
Hello Piercus.
Can you help with an issue I am having please?
I am plotting GPS Lat/Lon coordinates in a Google map. I have been trying to "smooth" the path using your Kalman filter but I am not progressing.

I started with the following filter settings:

		var   kFilter = new KalmanFilter({
			observation: 2,
			dynamic: 'constant-speed'
		});

And have progressed to using:

		const kFilter = new KalmanFilter({
	        observation: {
	                sensorDimension: 2,
	                sensorCovariance: 100,
	                name: 'sensor'
	        },
	        dynamic: {
	                name: 'constant-speed',
	                covariance: [1, 1, 0.01*5, 0.01*5]
	        }
		});

None of these are making very much difference to the path mapped.
I have created a CodePen here:
https://codepen.io/AnadiTaylor/pen/abByZLj

Any help and advice are gratefully received, thank you.

PS: In the above example I removed my Google API key, so please excuse the "This page can't load Google Maps correctly." warning.

**Comment by piercus** [comment]
@AnadiTaylor please check https://codepen.io/piercus/pen/wvoqPww

I did the following : 
* I have created 2 filter configs to compare the smoothing power
* Since the kalman filter observation covariance need to be huge on your example (i have used 1e10), i needed to set an initialization state to your first position + speed 0 to a huge [overshoot](https://en.wikipedia.org/wiki/Overshoot_(signal)) from the filter

Best

**Comment by AnadiTaylor** [comment]
Hello Pierre,
Thank you so much for this. I will integrate this into the full GPS data
and let you know how I get on.

You are a star!

All the best,
Anadi.



[image: Anadi James Taylor]    Anadi James Taylor
Suite 298
28 Old Brompton Road,
South Kensington,
London
SW7 3SS

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/22/21,
01:19:40 PM

**Comment by piercus** [comment]
Hello Anadi,

One more thing, currently you are using a simple forward filter (with `filterAll` method).
It means that the smooth result at iteration *i* is only using GPS data at iteration i and before.

The resulting curve is then 'late' compare to the data.
In order to correct this, it would be better to use a forward-backward kalman-filter.

I have opened an issue #11  regarding this, i will fix it in the next weeks.

**Comment by piercus** [comment]
I'm closing the issue

**Comment by AnadiTaylor** [comment]
Thank you Pierre,
I very much appreciate your help with this.

All the best,
Anadi.



[image: Anadi James Taylor]    Anadi James Taylor
Suite 298
28 Old Brompton Road,
South Kensington,
London
SW7 3SS

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
02/22/21,
02:45:23 PM
